// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Project.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20211203201204_People")]
    partial class People
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final_Project.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = "6-20-200",
                            FirstName = "David",
                            LastName = "Draginoff",
                            Major = "IT CyberSecurity",
                            Year = "junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = "4-4-1999",
                            FirstName = "Colton",
                            LastName = "Dalton",
                            Major = "IT Software Dev",
                            Year = "junior"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = "3-18-2000",
                            FirstName = "Alex",
                            LastName = "Gajic",
                            Major = "IT ",
                            Year = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = "5-1-2001",
                            FirstName = "Samuel",
                            LastName = "Untener",
                            Major = "IT Game Development and Simulation",
                            Year = "junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
