// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Project.Migrations
{
    [DbContext(typeof(MountainsContext))]
    [Migration("20211202013224_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final_Project.Models.Mountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightInFeet")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TallestMountains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Nepal",
                            HeightInFeet = 29029,
                            Name = "Mount Everest",
                            Parent = "N/A",
                            Range = "Mahalangur Himalaya"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Pakistan",
                            HeightInFeet = 28251,
                            Name = "K2",
                            Parent = "Mount Everest",
                            Range = "Baltoro Karakoram"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Nepal",
                            HeightInFeet = 28169,
                            Name = "Kangchenjunga",
                            Parent = "Mount Everest",
                            Range = "Kangchenjunga Himalaya"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Nepal",
                            HeightInFeet = 27940,
                            Name = "Lhoste",
                            Parent = "Mount Everest",
                            Range = "Mahalangur Himalaya"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Nepal",
                            HeightInFeet = 27838,
                            Name = "Makalu",
                            Parent = "Mount Everest",
                            Range = "Mahalangur Himalaya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
