// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Project.Migrations
{
    [DbContext(typeof(TallestTsunamisContext))]
    partial class TallestTsunamisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final_Project.Models.Tsunami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Element")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightInFeet")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Where")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TallestTsunamis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Element = "Water",
                            HeightInFeet = 1720,
                            Type = "Megatsunami",
                            Where = "Alaska",
                            Year = 1958
                        },
                        new
                        {
                            Id = 2,
                            Element = "Water",
                            HeightInFeet = 820,
                            Type = "Tsunami",
                            Where = "Washington",
                            Year = 1980
                        },
                        new
                        {
                            Id = 3,
                            Element = "Water",
                            HeightInFeet = 771,
                            Type = "Tsunami",
                            Where = "Italy",
                            Year = 1963
                        },
                        new
                        {
                            Id = 4,
                            Element = "Water",
                            HeightInFeet = 633,
                            Type = "Megatsunami",
                            Where = "Alaska",
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            Element = "Water",
                            HeightInFeet = 490,
                            Type = "Tsunami",
                            Where = "Alaska",
                            Year = 1936
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
